### ISSUE TITLE
Is this thing on? *tap* *tap*

### ISSUE THREAD

**Issue by stratigos** [bushwickfc/misc#1]
Hello all, 

This may not be the most appropriate means of contact, so feel free to close the issue. I can also be contacted via *techarchist@gmail.com*. 

However, I stopped trying to work with BFC a while back, as most of my communications, concerns, requests, and naturally, pull requests, were met with silence. I had quite a lot of problems regarding my hours that were always met with either silence or "we will look into it" (indefinitely), there diddnt seem to be anyone to respond to any kind of technical correspondence I made. I had just assumed the organization decided not to pursue technology development, and somewhere along the lines, my email got dropped out of related communications. Simultaneously, my needs as a BFC member were met with similar difficulties and blockages. I have heard there have been several changes in managerial structure, and assumed that had something to do with it.

So when I was invited to join this `misc` project today, I decided to reach out via Github, rather than email, since I havent had a response to my BFC emails in years. 

I have a lot of free time currently. Does this project have issues or features that need attention? I would like to contribute if there is anyone attending things over at BFC these days.

**Comment by Jamesripp** [comment]
Hey Todd, sorry about your troubles earlier, but yeah, we're checking it now. We switched over to a spreadsheet for tracking hours and fees as none of our members were able to figure out what was wrong with db.ov. I (James) am the current manager liaising with IT and would be happy to run through the current issues with you if you want to meet up sometime. We also now have a slack board where you can get in touch with other IT members: https://bushwickfoodcoop.slack.com/

Thanks for reaching out!
J

**Comment by stratigos** [comment]
Great thanks, Ill follow up via Slack.
